<?php 
define("Title","About Us");
define("Main","About Us");
include('header.php');
?>

<?php

    echo "<section class=\"ftco-section ftco-counter img\" id=\"section-counter\" style=\"background-image: url(images/bg_2.jpg);\">\n";
echo "    	<div class=\"container\">\n";
echo "    		<div class=\"row justify-content-center\">\n";
echo "    			<div class=\"col-md-10\">\n";
echo "		    		<div class=\"row\">\n";
echo "		          <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\n";
echo "		            <div class=\"block-18 text-center\">\n";
echo "		              <div class=\"text\">\n";
echo "		                <strong class=\"number\" data-number=\"50000\">0</strong>\n";
echo "		                <span>Happy Passengers</span>\n";
echo "		              </div>\n";
echo "		            </div>\n";
echo "		          </div>\n";
echo "		          <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\n";
echo "		            <div class=\"block-18 text-center\">\n";
echo "		              <div class=\"text\">\n";
echo "		                <strong class=\"number\" data-number=\"3000\">0</strong>\n";
echo "		                <span>Buses</span>\n";
echo "		              </div>\n";
echo "		            </div>\n";
echo "		          </div>\n";
echo "		          <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\n";
echo "		            <div class=\"block-18 text-center\">\n";
echo "		              <div class=\"text\">\n";
echo "		                <strong class=\"number\" data-number=\"1000\">0</strong>\n";
echo "		                <span>Staffs</span>\n";
echo "		              </div>\n";
echo "		            </div>\n";
echo "		          </div>\n";
echo "		          <div class=\"col-md-3 d-flex justify-content-center counter-wrap ftco-animate\">\n";
echo "		            <div class=\"block-18 text-center\">\n";
echo "		              <div class=\"text\">\n";
echo "		                <strong class=\"number\" data-number=\"100\">0</strong>\n";
echo "		                <span>Destination</span>\n";
echo "		              </div>\n";
echo "		            </div>\n";
echo "		          </div>\n";
echo "		        </div>\n";
echo "	        </div>\n";
echo "        </div>\n";
echo "    	</div>\n";
echo "    </section>\n";
echo "\n";
echo " <br><br>";
echo "    <section class=\"ftco-section ftc-no-pb ftc-no-pt\">\n";
echo "			<div class=\"container\">\n";
echo "				<div class=\"row\">\n";
echo "					<div class='col-md-5 p-md-5 img img-2 img-3 d-flex justify-content-center align-items-center' style='background-image: url(images/bus_4.jpg);'>";
echo "					</div>";
echo "					<div class=\"col-md-7 py-5 wrap-about pb-md-5 ftco-animate\">\n";
echo "	          <div class=\"heading-section heading-section-wo-line pt-md-5 pl-md-5 mb-5\">\n";
echo "	          	<div class=\"ml-md-0\">\n";
echo "		          	<span class=\"subheading\">Welcome to Busy Bus</span>\n";
echo "		            <h2 class=\"mb-4\">Welcome To Busy Bus Online Ticket System</h2>\n";
echo "	            </div>\n";
echo "	          </div>\n";
echo "	          <div class=\"pb-md-5\">\n";
echo "							<p>We help our customers organize their trips and daily commutes more easily.  Process bookings and payments online, manage your business more efficiently. Check the key features that come standard with the bus ticket reservation system. To request any other fine-tuning, just contact us!</p>\n";
echo "							<p>This is the easiest bus booking software to create routes with start, end and stop destinations, manage time traveling and bus schedules. Customers can pay both online and offline using various payment gateways (PayPal, Authorize.Net...), CC, wire transfers and cash. Customers can view ticket rates and discounts with our bus ticketing system. Booking reports and timetable daily schedule statistics help you keep track of bookings on a date-to-date basis. </p>\n";
echo "							<ul class=\"ftco-social d-flex\">\n";
echo "                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\n";
echo "                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\n";
echo "                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-google-plus\"></span></a></li>\n";
echo "                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\n";
echo "              </ul>\n";
echo "						</div>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</section>\n";
echo "		\n";
echo "		<section class=\"ftco-section\">\n";
echo "      <div class=\"container\">\n";
echo "        <div class=\"row d-flex\">\n";
echo "          <div class=\"col-md-3 d-flex align-self-stretch ftco-animate\">\n";
echo "            <div class=\"media block-6 services py-4 d-block text-center\">\n";
echo "              <div class=\"d-flex justify-content-center\">\n";
echo "              	<div class=\"icon d-flex align-items-center justify-content-center\">\n";
echo "              		<span class=\"flaticon-reception-bell\"></span>\n";
echo "              	</div>\n";
echo "              </div>\n";
echo "              <div class=\"media-body p-2 mt-2\">\n";
echo "                <h3 class=\"heading mb-3\">24/7 Customer Service</h3>\n";
echo "                <p>Our friendly customer service staff will be on call anytime, ready to serve you and solve your problems.</p>\n";
echo "              </div>\n";
echo "            </div>      \n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex align-self-stretch ftco-animate\">\n";
echo "            <div class=\"media block-6 services py-4 d-block text-center\">\n";
echo "              <div class=\"d-flex justify-content-center\">\n";
echo "              	<div class=\"icon d-flex align-items-center justify-content-center\">\n";
echo "              		<span class=\"flaticon-serving-dish\"></span>\n";
echo "              	</div>\n";
echo "              </div>\n";
echo "              <div class=\"media-body p-2 mt-2\">\n";
echo "                <h3 class=\"heading mb-3\">Bus Meals</h3>\n";
echo "                <p>Meals will be provided during your travel.</p>\n";
echo "              </div>\n";
echo "            </div>    \n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex align-sel Searchf-stretch ftco-animate\">\n";
echo "            <div class=\"media block-6 services py-4 d-block text-center\">\n";
echo "              <div class=\"d-flex justify-content-center\">\n";
echo "              	<div class=\"icon d-flex align-items-center justify-content-center\">\n";
echo "              		<span class=\"flaticon-car\"></span>\n";
echo "              	</div>\n";
echo "              </div>\n";
echo "              <div class=\"media-body p-2 mt-2\">\n";
echo "                <h3 class=\"heading mb-3\">Transfer Services</h3>\n";
echo "                <p>Taxis are available at every bus stops, made easier for transfer.</p>\n";
echo "              </div>\n";
echo "            </div>      \n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex align-self-stretch ftco-animate\">\n";
echo "            <div class=\"media block-6 services py-4 d-block text-center\">\n";
echo "              <div class=\"d-flex justify-content-center\">\n";
echo "              	<div class=\"icon d-flex align-items-center justify-content-center\">\n";
echo "              		<span class=\"flaticon-spa\"></span>\n";
echo "              	</div>\n";
echo "              </div>\n";
echo "              <div class=\"media-body p-2 mt-2\">\n";
echo "                <h3 class=\"heading mb-3\">VIP Previlleges</h3>\n";
echo "                <p>A lounge is available at most bus stations exclusove for VIP members only!</p>\n";
echo "              </div>\n";
echo "            </div>      \n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </section>";


    echo "<section class=\"instagram pt-5\">\n";
echo "      <div class=\"container-fluid\">\n";
echo "        <div class=\"row no-gutters justify-content-center pb-5\">\n";
echo "          <div class=\"col-md-7 text-center heading-section ftco-animate\">\n";
echo "            <h2><span>Instagram</span></h2>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"row no-gutters\">\n";
echo "          <div class=\"col-sm-12 col-md ftco-animate\">\n";
echo "            <a href=\"images/insta-1.jpg\" class=\"insta-img image-popup\" style=\"background-image: url(images/bus_12.jpg);\">\n";
echo "              <div class=\"icon d-flex justify-content-center\">\n";
echo "                <span class=\"icon-instagram align-self-center\"></span>\n";
echo "              </div>\n";
echo "            </a>\n";
echo "          </div>\n";
echo "          <div class=\"col-sm-12 col-md ftco-animate\">\n";
echo "            <a href=\"images/insta-2.jpg\" class=\"insta-img image-popup\" style=\"background-image: url(images/bus_7.jpg);\">\n";
echo "              <div class=\"icon d-flex justify-content-center\">\n";
echo "                <span class=\"icon-instagram align-self-center\"></span>\n";
echo "              </div>\n";
echo "            </a>\n";
echo "          </div>\n";
echo "          <div class=\"col-sm-12 col-md ftco-animate\">\n";
echo "            <a href=\"images/insta-3.jpg\" class=\"insta-img image-popup\" style=\"background-image: url(images/bus_9.jpg);\">\n";
echo "              <div class=\"icon d-flex justify-content-center\">\n";
echo "                <span class=\"icon-instagram align-self-center\"></span>\n";
echo "              </div>\n";
echo "            </a>\n";
echo "          </div>\n";
echo "          <div class=\"col-sm-12 col-md ftco-animate\">\n";
echo "            <a href=\"images/insta-4.jpg\" class=\"insta-img image-popup\" style=\"background-image: url(images/bus_10.jpg);\">\n";
echo "              <div class=\"icon d-flex justify-content-center\">\n";
echo "                <span class=\"icon-instagram align-self-center\"></span>\n";
echo "              </div>\n";
echo "            </a>\n";
echo "          </div>\n";
echo "          <div class=\"col-sm-12 col-md ftco-animate\">\n";
echo "            <a href=\"images/insta-5.jpg\" class=\"insta-img image-popup\" style=\"background-image: url(images/bus_3.jpg);\">\n";
echo "              <div class=\"icon d-flex justify-content-center\">\n";
echo "                <span class=\"icon-instagram align-self-center\"></span>\n";
echo "              </div>\n";
echo "            </a>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </section>\n";
echo "\n";
?>
<?php include('footer.php');?>