<?php 
define("Title","Career");
define("Main","Career");
include('header.php');
?>
<?php
echo"<br><br>";
echo"<table border='0' width='1000px' align='center'>";
echo"<tr>";
echo"<th width='490px'><h2 align='center'><a href='career.php' class='active'>Our Career</a></h2></th>";
echo"<th width='20px'><h2 align='center'>|</h2></th>";
echo"<th width='490px'><h2 align='center'><a href='job.php'>Join Us</a></h2></th>";
echo"</tr>";
echo"</table>";
echo"<br><br>";
echo "   <section class=\"ftco-section ftc-no-pb ftc-no-pt\">\n";
echo "			<div class=\"container\">\n";
echo "				<div class=\"row\">\n";
echo "					<div class=\"col-md-5 p-md-5 img img-2 img-3 d-flex justify-content-center align-items-center\" style=\"background-image: url(images/bus_13.jpg);\">\n";
echo "						<a href='https://vimeo.com/316155010' class=\"icon popup-vimeo d-flex justify-content-center align-items-center\">\n";
echo "							<span class=\"icon-play\"></span>\n";
echo "						</a>\n";
echo "					</div>";
echo "<div class=\"col-md-7 py-5 wrap-about pb-md-5 ftco-animate\">\n";
echo "	          <div class=\"heading-section heading-section-wo-line pt-md-5 pl-md-5 mb-5\">\n";
echo "	          	<div class=\"ml-md-0\">\n";
echo "		          	<span class=\"subheading\"></span>\n";
echo "		            <h1 class=\"mb-4\">Who We Are ?</h1>\n";
echo "	            </div>\n";
echo "	          </div>\n";
echo "	          <div class=\"pb-md-5\">\n";
echo "							<p>At BuzyBus.com, we make it easier for everyone to experience the world. We began by taking busses bookings online over 15 years ago and we’ve been shaping the travel industry ever since. Today, we’re building a platform that connects every part of a trip – from a great place to stay to getting there, getting around, seeing the sights and sampling local life.</p>";
echo "							<ul class=\"ftco-social d-flex\">\n";
echo "                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\n";
echo "                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\n";
echo "                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-google-plus\"></span></a></li>\n";
echo "                <li class=\"ftco-animate\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\n";
echo "              </ul>\n";
echo "						</div>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</section>";
echo "	<section class=\"ftco-section\">\n";
echo "      <div class=\"container\">\n";
echo "        <div class=\"row d-flex\">\n";
echo "          <div class=\"col-md-3 d-flex align-self-stretch ftco-animate\">\n";
echo "            <div class=\"media block-6 services py-4 d-block text-center\">\n";
echo "              <div class=\"d-flex justify-content-center\">\n";
echo "              	<div class=\"icon d-flex align-items-center justify-content-center\">\n";
echo "                  <span class=\"icon-clock-o\"></span>\n";
echo "              	</div>\n";
echo "              </div>\n";
echo "              <div class=\"media-body p-2 mt-2\">\n";
echo "                <h3 class=\"heading mb-3\">Own It</h3>\n";
echo "                <p>We deliver on our promises, make informed decisions and prioritize to get important things done today.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex align-self-stretch ftco-animate\">\n";
echo "            <div class=\"media block-6 services py-4 d-block text-center\">\n";
echo "              <div class=\"d-flex justify-content-center\">\n";
echo "              	<div class=\"icon d-flex align-items-center justify-content-center\">\n";
echo "              		<span class=\"icon-gear\"></span>\n";
echo "              	</div>\n";
echo "              </div>\n";
echo "              <div class=\"media-body p-2 mt-2\">\n";
echo "                <h3 class=\"heading mb-3\">Learn Forever</h3>\n";
echo "                <p>We are resilent, take time to reflect, and seek to learn - from colleagues, from the outside world and from ur failures..</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex align-sel Searchf-stretch ftco-animate\">\n";
echo "            <div class=\"media block-6 services py-4 d-block text-center\">\n";
echo "              <div class=\"d-flex justify-content-center\">\n";
echo "              	<div class=\"icon d-flex align-items-center justify-content-center\">\n";
echo "              	<span class=\"icon-comment\"></span>\n";
echo "              	</div>\n";
echo "              </div>\n";
echo "              <div class=\"media-body p-2 mt-2\">\n";
echo "                <h3 class=\"heading mb-3\">Think Customer First</h3>\n";
echo "                <p>We obsess about adding value for our customer - guests, partners, colleagues, - to make it more easier to everyone to experience the world.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex align-self-stretch ftco-animate\">\n";
echo "            <div class=\"media block-6 services py-4 d-block text-center\">\n";
echo "              <div class=\"d-flex justify-content-center\">\n";
echo "              	<div class=\"icon d-flex align-items-center justify-content-center\">\n";
echo "              		<span class=\"icon-check\"></span>\n";
echo "              	</div>\n";
echo "              </div>\n";
echo "              <div class=\"media-body p-2 mt-2\">\n";
echo "                <h3 class=\"heading mb-3\">Do The Right Thing</h3>\n";
echo "                <p>We get the right results the right way. For each other, our communities and the world around us.</p>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </section>";
echo "<section class=\"ftco-section ftc-no-pb ftc-no-pt\">\n";
echo "      <div class=\"container\">\n";
echo "        <div class=\"row\">\n";
echo "          <div class=\"col-md-5 p-md-5 img img-2 img-3 d-flex justify-content-center align-items-center\" style=\"background-image: url(images/staff-2.jpg);\">\n";
echo "          </div>\n";
echo "          <div class=\"col-md-7 py-5 wrap-about pb-md-5 ftco-animate\">\n";
echo "            <div class=\"heading-section heading-section-wo-line pt-md-4 mb-5\">\n";
echo "              <div class=\"ml-md-0\">\n";
echo "                <span class=\"subheading\">James Khoo</span>\n";
echo "                <h2 class=\"mb-4\">Founder of BUSY BUS</h2>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "            <div class=\"pb-md-4\">\n";
echo "              <p>One of Asia’s most recognisable entrepreneurs, James Khoo is best known for co-founding low-cost carrier BUZY BUS with Datuk Jonathan Lim and democratising land travel in the region.</p>\n";
echo "              <p class=\"pl-md-5\">James Khoo famously bought the busses company for a token MYR1 (approximately USD0.25) and MYR40 million in debt, turning it around within two years and growing it from a Malaysian domestic carrier into Asia’s largest low-cost carrier by passengers carried.</p>\n";
echo "              <p>James studied in the UK, and qualified as an Associate Member of the Association of Chartered Certified Accountants in 1991 and Fellow Member in 1996. An accountant by training, He began his career in Richard Branson’s Virgin Group before returning to Malaysia as Warner Music Group’s Vice President for Southeast Asia before venturing into the landline business..</p>\n";
echo "              <h1 align=\"center\"><span>“</span></h1>\n";
echo "              <p>I'm still challenged everyday to do better, to be open and to be humble, to say that tomorrow I still need to learn something else in order to make the company more better. - James Khoo</p>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </section>";
echo " <section class=\"ftco-section testimony-section bg-light\">\n";
echo "      <div class=\"container\">\n";
echo "        <div class=\"row justify-content-center\">\n";
echo "          <div class=\"col-md-8 ftco-animate\">\n";
echo "            <div class=\"row ftco-animate\">\n";
echo "              <div class=\"col-md-12\">\n";
echo "                <div class=\"carousel-testimony owl-carousel ftco-owl\">\n";
echo "                  <div class=\"item\">\n";
echo "                    <div class=\"testimony-wrap py-4 pb-5\">\n";
echo "                      <div class=\"user-img mb-4\" style=\"background-image: url(images/person_1.jpg)\">\n";
echo "                        <span class=\"quote d-flex align-items-center justify-content-center\">\n";
echo "                          <i class=\"icon-quote-left\"></i>\n";
echo "                        </span>\n";
echo "                      </div>\n";
echo "                      <div class=\"text text-center\">\n";
echo "                        <p class=\"mb-4\">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\n";
echo "                        <p class=\"name\">Nathan Smith</p>\n";
echo "                        <span class=\"position\">Guests</span>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"item\">\n";
echo "                    <div class=\"testimony-wrap py-4 pb-5\">\n";
echo "                      <div class=\"user-img mb-4\" style=\"background-image: url(images/person_2.jpg)\">\n";
echo "                        <span class=\"quote d-flex align-items-center justify-content-center\">\n";
echo "                          <i class=\"icon-quote-left\"></i>\n";
echo "                        </span>\n";
echo "                      </div>\n";
echo "                      <div class=\"text text-center\">\n";
echo "                        <p class=\"mb-4\">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\n";
echo "                        <p class=\"name\">Nathan Smith</p>\n";
echo "                        <span class=\"position\">Guests</span>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"item\">\n";
echo "                    <div class=\"testimony-wrap py-4 pb-5\">\n";
echo "                      <div class=\"user-img mb-4\" style=\"background-image: url(images/person_3.jpg)\">\n";
echo "                        <span class=\"quote d-flex align-items-center justify-content-center\">\n";
echo "                          <i class=\"icon-quote-left\"></i>\n";
echo "                        </span>\n";
echo "                      </div>\n";
echo "                      <div class=\"text text-center\">\n";
echo "                        <p class=\"mb-4\">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\n";
echo "                        <p class=\"name\">Nathan Smith</p>\n";
echo "                        <span class=\"position\">Guests</span>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"item\">\n";
echo "                    <div class=\"testimony-wrap py-4 pb-5\">\n";
echo "                      <div class=\"user-img mb-4\" style=\"background-image: url(images/person_1.jpg)\">\n";
echo "                        <span class=\"quote d-flex align-items-center justify-content-center\">\n";
echo "                          <i class=\"icon-quote-left\"></i>\n";
echo "                        </span>\n";
echo "                      </div>\n";
echo "                      <div class=\"text text-center\">\n";
echo "                        <p class=\"mb-4\">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\n";
echo "                        <p class=\"name\">Nathan Smith</p>\n";
echo "                        <span class=\"position\">Guests</span>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                  <div class=\"item\">\n";
echo "                    <div class=\"testimony-wrap py-4 pb-5\">\n";
echo "                      <div class=\"user-img mb-4\" style=\"background-image: url(images/person_1.jpg)\">\n";
echo "                        <span class=\"quote d-flex align-items-center justify-content-center\">\n";
echo "                          <i class=\"icon-quote-left\"></i>\n";
echo "                        </span>\n";
echo "                      </div>\n";
echo "                      <div class=\"text text-center\">\n";
echo "                        <p class=\"mb-4\">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>\n";
echo "                        <p class=\"name\">Nathan Smith</p>\n";
echo "                        <span class=\"position\">Guests</span>\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                  </div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </section>";
?>
<?php include('footer.php');?>