<?php 
define("Title","News");
define("Main","News");
include('header.php');
?>
<?php
echo "    <section class=\"ftco-section\">\n";
echo "      <div class=\"container\">\n";
echo "        <div class=\"row d-flex\">\n";
echo "          <div class=\"col-md-3 d-flex ftco-animate\">\n";
echo "            <div class=\"blog-entry align-self-stretch\">\n";
echo "              <a href=\"blog-single.php\" class=\"block-20\" style=\"background-image: url('images/new_1.jpg');width:250px\">\n";
echo "              </a>\n";
echo "              <div class=\"text mt-3 d-block\">\n";
echo "                <h3 class=\"heading mt-3\"><a href=\"#\">How to take a ride?</a></h3>\n";
echo "                <div class=\"meta mb-3\">\n";
echo "                  <div><a href=\"#\">Dec 6, 2018</a></div>\n";
echo "                  <div><a href=\"#\">Admin</a></div>\n";
echo "                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>";

          echo "<div class=\"col-md-3 d-flex ftco-animate\">\n";
echo "            <div class=\"blog-entry align-self-stretch\">\n";
echo "              <a href=\"blog-single.php\" class=\"block-20\" style=\"background-image: url('images/new_2.jpg');width:250px\">\n";
echo "              </a>\n";
echo "              <div class=\"text mt-3\">\n";
echo "                <h3 class=\"heading mt-3\"><a href=\"#\">How to book a ticket?</a></h3>\n";
echo "                <div class=\"meta mb-3\">\n";
echo "                  <div><a href=\"#\">Dec 6, 2018</a></div>\n";
echo "                  <div><a href=\"#\">Admin</a></div>\n";
echo "                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex ftco-animate\">\n";
echo "            <div class=\"blog-entry align-self-stretch\">\n";
echo "              <a href=\"blog-single.php\" class=\"block-20\" style=\"background-image: url('images/new_3.jpg');width:250px\">\n";
echo "              </a>\n";
echo "              <div class=\"text mt-3\">\n";
echo "                <h3 class=\"heading mt-3\"><a href=\"#\">VIP Previlleges</a></h3>\n";
echo "                <div class=\"meta mb-3\">\n";
echo "                  <div><a href=\"#\">Dec 6, 2018</a></div>\n";
echo "                  <div><a href=\"#\">Admin</a></div>\n";
echo "                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex ftco-animate\">\n";
echo "            <div class=\"blog-entry align-self-stretch\">\n";
echo "              <a href=\"blog-single.php\" class=\"block-20\" style=\"background-image: url('images/new_4.jpg');width:250px\">\n";
echo "              </a>\n";
echo "              <div class=\"text mt-3\">\n";
echo "                <h3 class=\"heading mt-3\"><a href=\"#\">Meals provided during travel</a></h3>\n";
echo "                <div class=\"meta mb-3\">\n";
echo "                  <div><a href=\"#\">Dec 6, 2018</a></div>\n";
echo "                  <div><a href=\"#\">Admin</a></div>\n";
echo "                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex ftco-animate\">\n";
echo "            <div class=\"blog-entry align-self-stretch\">\n";
echo "              <a href=\"blog-single.php\" class=\"block-20\" style=\"background-image: url('images/new_5.jpg');width:250px\">\n";
echo "              </a>\n";
echo "              <div class=\"text mt-3 d-block\">\n";
echo "                <h3 class=\"heading mt-3\"><a href=\"#\">How to contact our customer service?</a></h3>\n";
echo "                <div class=\"meta mb-3\">\n";
echo "                  <div><a href=\"#\">Dec 6, 2018</a></div>\n";
echo "                  <div><a href=\"#\">Admin</a></div>\n";
echo "                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex ftco-animate\">\n";
echo "            <div class=\"blog-entry align-self-stretch\">\n";
echo "              <a href=\"blog-single.php\" class=\"block-20\" style=\"background-image: url('images/new_6.jpg');width:250px\">\n";
echo "              </a>\n";
echo "              <div class=\"text mt-3\">\n";
echo "                <h3 class=\"heading mt-3\"><a href=\"#\">Routes of bus</a></h3>\n";
echo "                <div class=\"meta mb-3\">\n";
echo "                  <div><a href=\"#\">Dec 6, 2018</a></div>\n";
echo "                  <div><a href=\"#\">Admin</a></div>\n";
echo "                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>";

          echo "<div class=\"col-md-3 d-flex ftco-animate\">\n";
echo "            <div class=\"blog-entry align-self-stretch\">\n";
echo "              <a href=\"blog-single.php\" class=\"block-20\" style=\"background-image: url('images/new_7.jpg');width:250px\">\n";
echo "              </a>\n";
echo "              <div class=\"text mt-3\">\n";
echo "                <h3 class=\"heading mt-3\"><a href=\"#\">Schedule of bus</a></h3>\n";
echo "                <div class=\"meta mb-3\">\n";
echo "                  <div><a href=\"#\">Dec 6, 2018</a></div>\n";
echo "                  <div><a href=\"#\">Admin</a></div>\n";
echo "                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "          <div class=\"col-md-3 d-flex ftco-animate\">\n";
echo "            <div class=\"blog-entry align-self-stretch\">\n";
echo "              <a href=\"blog-single.php\" class=\"block-20\" style=\"background-image: url('images/new_8.jpg');width:250px\">\n";
echo "              </a>\n";
echo "              <div class=\"text mt-3\">\n";
echo "                <h3 class=\"heading mt-3\"><a href=\"#\">Travel Notice(Covid-19)</a></h3>\n";
echo "                <div class=\"meta mb-3\">\n";
echo "                  <div><a href=\"#\">Dec 6, 2018</a></div>\n";
echo "                  <div><a href=\"#\">Admin</a></div>\n";
echo "                  <div><a href=\"#\" class=\"meta-chat\"><span class=\"icon-chat\"></span> 3</a></div>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"row mt-5\">\n";
echo "          <div class=\"col text-center\">\n";
echo "            <div class=\"block-27\">\n";
echo "              <ul>\n";
echo "                <li><a href=\"#\"><</a></li>\n";
echo "                <li class=\"active\"><span>1</span></li>\n";
echo "                <li><a href=\"#\">2</a></li>\n";
echo "                <li><a href=\"#\">3</a></li>\n";
echo "                <li><a href=\"#\">4</a></li>\n";
echo "                <li><a href=\"#\">5</a></li>\n";
echo "                <li><a href=\"#\">></a></li>\n";
echo "              </ul>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </section>\n";
echo "\n";
?>
<?php include('footer.php');?>